---
driver:
  name: vagrant


provisioner:
  name: chef_zero

platforms:
- name: debian-7.4
  run_list:
  - recipe[apt::default]
  driver_config:
    provision_command:
    - apt-get update
    - apt-get install cron -y

suites:
  - name: default
    run_list:
      - recipe[site-gittypo3org::default]
    attributes:
      # this makes chef-vault use plaintext data bags
      dev_mode: true
      site-gittypo3org:
        amqp:
          server: mq.typo3.vagrant
          user: gittypo3org
      gitweb:
        ssl_certificate: "wildcard.vagrant"